# Use Python 3.10.19 base image
FROM python:3.10.19-slim

# Set working directory
WORKDIR /main

# Copy requirements and install dependicies
COPY requirements.txt .
RUN pip install --no--cache-dir -r requirements.txt

# Copy rest of application code
COPY . .

# Expose the application port
EXPOSE 8000

# command to start FastAPI application
CMD [ "uvicorn", "app:main", "--host", "0.0.0.0", "--port", "8000" ]